"""Added account table

Revision ID: a6a3226379c4
Revises: 
Create Date: 2021-02-05 10:44:56.659598

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a3226379c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAccounts_Role',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_removed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_UserAccounts_Role_description'), 'UserAccounts_Role', ['description'], unique=False)
    op.create_index(op.f('ix_UserAccounts_Role_name'), 'UserAccounts_Role', ['name'], unique=True)
    op.create_index(op.f('ix_UserAccounts_Role_slug'), 'UserAccounts_Role', ['slug'], unique=True)
    op.create_table('UserAccounts_User',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('item_removed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('middle_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('avatar', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_legal_person', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['UserAccounts_Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_UserAccounts_User_address'), 'UserAccounts_User', ['address'], unique=False)
    op.create_index(op.f('ix_UserAccounts_User_email'), 'UserAccounts_User', ['email'], unique=True)
    op.create_index(op.f('ix_UserAccounts_User_first_name'), 'UserAccounts_User', ['first_name'], unique=False)
    op.create_index(op.f('ix_UserAccounts_User_last_name'), 'UserAccounts_User', ['last_name'], unique=False)
    op.create_index(op.f('ix_UserAccounts_User_middle_name'), 'UserAccounts_User', ['middle_name'], unique=False)
    op.create_index(op.f('ix_UserAccounts_User_phone'), 'UserAccounts_User', ['phone'], unique=False)
    op.create_index(op.f('ix_UserAccounts_User_user_uuid'), 'UserAccounts_User', ['user_uuid'], unique=True)
    op.create_index(op.f('ix_UserAccounts_User_username'), 'UserAccounts_User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserAccounts_User_username'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_user_uuid'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_phone'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_middle_name'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_last_name'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_first_name'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_email'), table_name='UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_User_address'), table_name='UserAccounts_User')
    op.drop_table('UserAccounts_User')
    op.drop_index(op.f('ix_UserAccounts_Role_slug'), table_name='UserAccounts_Role')
    op.drop_index(op.f('ix_UserAccounts_Role_name'), table_name='UserAccounts_Role')
    op.drop_index(op.f('ix_UserAccounts_Role_description'), table_name='UserAccounts_Role')
    op.drop_table('UserAccounts_Role')
    # ### end Alembic commands ###
